name: Send Repo Name

on:
  push:
    tags:
      - v1.**

jobs:
  send-repo-template:
    uses: techupth/techupth-workflows/.github/workflows/send-assignment-submit-result-template.yml@main
    secrets: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AUTH_GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
